---
title: "Skagit qPCR methods"
author: "Ole Shelton"
date: "8/14/2018"
output: pdf_document
---
### DNA Extraction

Modified from:

*Renshaw MA et al. (2015) The room temperature preservation of filtered environmental DNA samples and assimilation into a phenol–chloroform–isoamyl alcohol DNA extraction. Mol Ecol Resour, 15: 168–176. doi:10.1111/1755-0998.12281*

Input: 47mm cellulose nitrate filter in 1000uL of Longmire buffer in a 2mL centrifuge tube

Remember to include controls:
  - 1 using only clean Longmire solution (noDNA), with volume equal to other samples
  - 1 using tissue in Longmire solution

Most of these steps are to be done in a hood. Phenol is really dangerous, and so is chloroform.

**REAGENTS** (per N samples)
- phenol:chloroform:isoamyl alcohol (25:24:1) aka "PCI" (900uL)
- chloroform or chloroform:isoamyl 24:1 (1400uL)
- 5M NaCl (20uL)
- isopropanol aka 2-propanol 99.9% (500uL)
- PCR grade water (200uL)

**CONSUMABLES** (per N samples)
- 1.5mL tubes (1N)
- 2mL tubes (2N)
- 1000uL filter tips (4N)
- 10uL filter tips (1)

**EQUIPMENT**
- fume hood
- incubator (water bath or oven)
- centrifuge
- dryer
- pipettes (1000uL, 100uL or 20uL, 10uL)

<div style="page-break-after: always;"></div>

**PROCEDURE**

*Day 1*

P1. Preheat the incubator (takes ~30 min)

P2. Get out all your reagents and supplies (pipette tips, etc)

1. Spin the samples briefly to ensure the filter is squished down to the bottom of the tube with no air bubbles. The tubes end up being really full, so this is important.

2. Incubate samples at 65ºC for 30 minutes.

3. While the samples are in the incubator:
    - Add 700uL chloroform to each of two sets of 2mL tubes. Label them (sequential numbers are fine, these aren't the final tubes), and set aside.
    - Add 20uL of 5M NaCl and 500uL of isopropanol to a fresh set of 1.5mL tubes. Label (these are the final tubes) and put in the freezer.

4. After incubation (turn off the incubator!), add 800uL of phenol:chloroform:isoamyl alcohol to each tube.

5. Shake the tubes vigorously for 60 seconds.

6. Centrifuge at 17.0*g for 5 minutes.

7. Remove as much as possible of the aqueous (top) layer, transfer to first set of tubes containing 700uL chloroform (was 750uL).

8. Shake the tubes vigorously for 60 seconds.

9. Centrifuge at 17.0*g for 5 minutes

10. Remove as much as possible of the aqueous (top) layer, transfer to the second set of tubes containing 700uL chloroform.

11. Shake the tubes vigorously for 60 seconds.

12. Centrifuge at 17.0*g for 5 minutes.

13. Transfer 900uL of the aqueous (top) layer to the tubes containing the isopropanol/NaCl mixture.

14. Allow to precipitate at -20ºC overnight (16 hours).

*Day 2*

15. Centrifuge tubes at 17.0*g for 30 minutes.

16. While those centrifuge, set out some clean Kimwipes and a small vessel to contain the salt/isopropanol solution.

17. Pour off liquid slowly, and set the tube upside-down on the clean Kimwipe.

18. Using a 10uL pipette with a clean tip, dab off and remove any drops.

19. Set in a tube rack and let dry in the hood for 2 hours.

20. Add 200uL PCR-grade water.

21. Vortex to dissolve DNA; spin very briefly to get liquid down from cap.

\pagebreak

### Purification of Genomic DNA by Ethanol Precipitation
Kim Parsons Protocol modified by Jimmy O'Donnell

### Materials Needed
- 95% Ethanol 
- 70% Ethanol 
- 5M NaCl
- Sterile Water

**Precipitate the DNA**
1. Add 2.5 times your DNA sample volume of 95% cold ethanol. For example, if you started with 50 μl of DNA solution, use 125 μL of 95% ethanol. Total volume should not exceed 1.5mL.
2. Add 1/10 of the original sample volume of 5M NaCl. Again if we started with 100 μl of gDNA, we’ll add 10 μl of 5M NaCl.
3. Mix by quickly inverting several times until well combined. You may see a “cloudy” or “cotton ball-like” precipitate begin to form at this point.
4. Put the tubes at -20ºC overnight to facilitate precipitation. 
5. Spin for 20 minutes at 14000 rpm in a centrifuge. Orient tubes hinge out so the pellet forms in the same spot in each tube.
6. Remove the supernatant liquid from the tubes by pouring while making sure not to disturb the pellet, followed by carefully dabbing out any droplets with a pipette. You may see a small white or translucent pellet at this point. If not, assume it is where you expect it to be.

**Wash the Pellet**
1. Add 500 μl of 70% ethanol. You may wish to try to dislodge the pellet by aiming directly above the pellet, and expelling forcefully. Invert several times to thoroughly wash.
2. Spin for 5 minutes at 13-14k rpm. 
3. Remove the supernatant liquid from the tubes by pouring carefully while making sure not to disturb/lose the pellet. 
4. Repeat steps 1-3 if a second wash is desired.
5. Air-dry the pellets just until ethanol is no longer visible, but pellet doesn’t yet look dry or cracked, about 5-10 minutes (or up to an hour). Over-drying will lead to difficulty in resuspending the DNA.

**Resuspend the DNA**
1. Resuspend the DNA by adding 200uL of nuclease-free water or 10mM Tris pH 7.5 - 8.5 and pipetting up and down to mix. If you can dislodge the pellet while doing this, resuspension will be faster. 


